GET http://localhost:3000/posts
Authorization: Bearer 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTm92YSIsImlhdCI6MTY1NzE5MDM4OX0.nbF-iNJrZLyu5EiL3bfgEY1MOdOScmUTcaweLeEFUEU
###

POST  http://localhost:3000/login
Content-Type: application/json
{
    "username":"Nova"
}